// Generated by CoffeeScript 1.8.0
(function() {
  var doc, ready, readyStateChange;

  doc = window.document;

  ready = function() {
    var SCROLLBAR_WIDTH, div1, div2;
    div1 = doc.createElement('div');
    div1.style.width = '100px';
    div1.style.overflowX = 'scroll';
    div2 = doc.createElement('div');
    div2.style.width = '100px';
    doc.body.appendChild(div1);
    doc.body.appendChild(div2);
    SCROLLBAR_WIDTH = div1.offsetHeight - div2.offsetHeight;
    doc.body.removeChild(div1);
    doc.body.removeChild(div2);
    return window.SCROLLBAR_WIDTH = SCROLLBAR_WIDTH;
  };

  readyStateChange = function() {
    if (doc.readyState === 'complete') {
      return ready();
    }
  };

  if (typeof doc.addEventListener === "function") {
    doc.addEventListener('DOMContentLoaded', ready, false);
  }

  if (typeof window.addEventListener === "function") {
    window.addEventListener('load', ready, false);
  }

  if (typeof doc.attachEvent === "function") {
    doc.attachEvent('onreadystatechange', readyStateChange);
  }

  if (typeof window.attachEvent === "function") {
    window.attachEvent('onload', ready);
  }

}).call(this);
