// Generated by CoffeeScript 1.8.0
(function(root) {
  var doc, ready, readyStateChange;
  doc = root.document;
  ready = function() {
    var SCROLLBAR_WIDTH, div1, div2;
    div1 = doc.createElement('div');
    div1.style.width = '100px';
    div1.style.overflowX = 'scroll';
    div2 = doc.createElement('div');
    div2.style.width = '100px';
    doc.body.appendChild(div1);
    doc.body.appendChild(div2);
    SCROLLBAR_WIDTH = div1.offsetHeight - div2.offsetHeight;
    doc.body.removeChild(div1);
    doc.body.removeChild(div2);
    return root.SCROLLBAR_WIDTH = SCROLLBAR_WIDTH;
  };
  readyStateChange = function() {
    if (doc.readyState === 'complete') {
      return ready();
    }
  };
  if (typeof doc.addEventListener === "function") {
    doc.addEventListener('DOMContentLoaded', ready, false);
  }
  if (typeof root.addEventListener === "function") {
    root.addEventListener('load', ready, false);
  }
  if (typeof doc.attachEvent === "function") {
    doc.attachEvent('onreadystatechange', readyStateChange);
  }
  return typeof root.attachEvent === "function" ? root.attachEvent('onload', ready) : void 0;
})(this);
