// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var factory;

  factory = function(doc) {
    var scrollbarWidth;
    scrollbarWidth = null;
    return function(recalculate) {
      var div1, div2;
      if (recalculate == null) {
        recalculate = false;
      }
      if ((scrollbarWidth != null) && !recalculate) {
        return scrollbarWidth;
      }
      if (doc.readyState === 'loading') {
        return null;
      }
      div1 = doc.createElement('div');
      div2 = doc.createElement('div');
      div1.style.width = div2.style.width = div1.style.height = div2.style.height = '100px';
      div1.style.overflow = 'scroll';
      div2.style.overflow = 'hidden';
      doc.body.appendChild(div1);
      doc.body.appendChild(div2);
      scrollbarWidth = Math.abs(div1.scrollHeight - div2.scrollHeight);
      doc.body.removeChild(div1);
      doc.body.removeChild(div2);
      return scrollbarWidth;
    };
  };

  (function(root, factory) {
    if (root.document == null) {
      return console.warn('WARNING: root.document doesn\'t exist');
    }
    if (typeof define === 'function' && define.amd) {
      return define([], function() {
        return factory(root.document);
      });
    } else if (typeof exports !== 'undefined') {
      return module.exports = factory(root.document);
    } else {
      return root.getScrollbarWidth != null ? root.getScrollbarWidth : root.getScrollbarWidth = factory(root.document);
    }
  })(this, factory);

}).call(this);
